# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e1f51c9bee83c71d351e3893c986abcb5d7a4b46817f59695efb85af232c7ac3cecdc32d03a11d09620e3f10beca0ba48008ed008572043c4cc2a9fcb3364e8

test:
  secret_key_base: 3ad1c5a6af21b8e92071d8531c5dc168062989d3533e27414a88c89f3a5261daa9a09186f9a5bdaae9fc9b0ea85ab9ac2460d05a09ba78097b55a9cb473162a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
